<?php
/**
 * @file
 * Specifies rules for restricting user registration based on email domains.
 * Got this from here: http://drupal.org/node/1405368
 */

 function registration_restriction_admin() {
   $form = array();

   $form['registration_restriction_valid_domains'] = array(
    '#type' => 'textarea',
    '#title' => t('Email domains'),
    '#default_value' => variable_get('registration_restriction_valid_domains'),
    '#description' => t('Enter in email domains (the part after the "@" symbol). Seperate each with a comma, i.e. "drexel.edu, umass.edu."'),
    '#required' => TRUE,
    );

   $form['registration_restriction_type'] = array(
    '#type' => 'checkbox',
    '#title' => t('Blacklist listed domains'),
    '#description' => t('Check to blacklist these email domains (i.e. allow all domains EXCEPT ones listed here). The default is whitelist.'),
    '#default_value' => variable_get('registration_restriction_type'),
    '#return_value' => 'blacklist',
    );

   $form['registration_restriction_error_message'] = array(
    '#type' => 'textfield',
    '#title' => t('Invalid email domain message'),
    '#default_value' => variable_get('registration_restriction_error_message'),
    '#size' => 100,
    '#description' => t('This text is displayed when a user puts in an invalid email domain'),
    '#required' => TRUE,
   );

   return system_settings_form($form);
 }

 function registration_restriction_menu() {
   $items = array();

   $items['admin/config/people/registration-restriction'] = array(
    'title' => t('Registration Restriction module settings'),
    'description' => t('Settings for restricting userregistration to spcified email domains'),
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('registration_restriction_admin'),
    'access arguments' => array('administer registration_restriction settings'),
    'type' => MENU_NORMAL_ITEM,
   );

   return $items;
 }

 // Helper function to remove whitespace
 
 function trim_value(&$value) {
     $value = trim($value);
 }

 // Helper function for checking valid emails

 function registration_restriction_is_restricted_domain($domain, $listed_domains) {
   if (variable_get('registration_restriction_type') == 'blacklist') {
     if ( in_array($domain, $listed_domains) ) {
       return TRUE;
     } else {
       return FALSE;
     }
   } else {
     if ( !in_array($domain, $listed_domains) ) {
       return TRUE;
     } else {
       return FALSE;
     }
   }
 }


  function registration_restriction_form_alter(&$form, &$form_state, $form_id) {

  // make sure this is the register form
    if ($form_id == 'user_register_form') {
  // this adds your custom validation function to the form validation array
     $form['#validate'][] = 'registration_restriction_user_register_validation';
    }
  }

  function registration_restriction_user_register_validation($form, &$form_state) {
  // Valid Domains from configuration form
    $listed_domains = explode(",", variable_get('registration_restriction_valid_domains'));
    array_walk($listed_domains, 'trim_value');

  // Get domain 
        $email = $form_state['values']['mail'];
        $splitIndex = strpos($email, '@')+1;
        $emailLength = strlen($email);
        $domain = substr($email, $splitIndex, $emailLength);
        
  // Error if not legitimate domain  
    if ( registration_restriction_is_restricted_domain($domain, $listed_domains) ) {
      
     $message = variable_get('registration_restriction_error_message');

     form_set_error('mail', $message);
    }
  }
